### ISSUE TITLE
Allow artifact extraction

### ISSUE THREAD

**Issue by poldi1405** [metroline/metroline#13]
Hello,
right now I could only think of uploading it to a server in a separate step. At least I did not find anything in the docs.

So my proposal:
- create a new array `upload` containing either 
    - upload-urls (`sftp://user:password@host:port/path`)
    - refs to a "container-type" (that contains a type and the required/possible fields)
- add a new array `artifacts`
    - containing `files` with or without wildcards

**Comment by gempain** [comment]
Hi there ! Thanks for open an issue on our repository 😄 

I'd like to clarify what you want exactly. In my understanding, what you are describing is that you want a way to extract build artifacts from the build workspace, correct ?

Gitlab has a concept of artifacts in which you specify at the job level the paths you want to extract, and then lets you download them through the interface. This feature does not exist in Metroline at this time.

As you mentioned, you could do this in a step and upload it somewhere, but will agree that this isn't ideal. We need to have a way to tell Metroline to extract artifacts and keep them for a given amount of time (could be specified at the job, build or instance level).

I'm totally for having:

```
jobs:
  test:
    artifacts:
      # paths to be extracted
      paths:
        - ./my-file.ts
        - my-dir
      # expiration (in seconds)
      expiration: 86400
```

Artifacts will be stored by-job, and would be accessible from the UI.

What do you think ?
