### ISSUE TITLE
Allow multiple runners with different "tags"

### ISSUE THREAD

**Issue by poldi1405** [metroline/metroline#14]
We live in a world of many OSes, but cross-compilation is still a hassle in most languages. (like c++, which I need) So my idea would be: to allow multiple runner which can be supplied with tags. What I mean: you can't run windows-container on a linux maschine without virtualizing a complete windows stack (which I am ready to do). The server itself should remain on linux. (for performance reasons and ease of administration)

docker-compose.yml
```
  runner-win:
    image: metroline/runner:latest
    restart: unless-stopped
    environment:
      METROLINE_SERVER_ADDRESS: https://git.company.stuff/cibackend/
      METROLINE_RUNNER_SECRET: ${CIRUNNERSECRET}
      METROLINE_RUNNER_TAGS: windows,controlled-by-borg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

.metroline.yml
```
jobs:
  build-windows:
    image: purplekarrot/mingw-w64-x86-64
    runner-tags:
      - windows
    script:
      - make build
  build-linux:
    image: kitware/cmake
    runner-tags:
      - linux
    script:
      - make build
```

**Comment by gempain** [comment]
This one has been on our roadmap for a while, including multi-machine runners. You can already have runners on Windows (not tested, but I don't see why it wouldn't work), but all runners **must** be on the **same** machine, it's a known limitation. Runner labels are easy to introduce, but though your example suggests otherwise, would it be sufficient for you if you can specify it at the build level (not at the job level) ? This would imply that you **could** build on multiple OSes, **but** you would be forced to run all jobs of a build on the same OS (which is currently the case anyway).

The reason behind not introducing it at the job level is that the build workspace is shared between all jobs by re-using the same docker volume. If we allow choosing the runner at the job level, we would have to implement the logic for copying workspaces from one machine to another (that's the easy part, and we have a TODO somewhere in the code for this) and then figuring out **where** and **how** to merge workspaces of parallel jobs once they branch back together on a single job (hope this makes sense to you). That second part is the difficult one which I've been pushing back since the beginning as it brings a bunch of additional complexity - but we will eventually have to implement it.

**Comment by poldi1405** [comment]
> would it be sufficient for you if you can specify it at the build level
sufficient, yes. but not preferable. I'd rather keep the Windows VM lean (as far as this is possible)

> how to merge workspaces of parallel jobs
I see the issue, what if both runners create file x and it's different. My first idea (which probably wouldn't be so great) would be to define a "priority"-volume and allowing specific overwrites on the others. but this would also be one hell to implement. And if a user was especially unwilling to configure it could lead to even more issues.

**Comment by gempain** [comment]
Then I guess it's a good occasion to do it all at once, implement runner tags and multi-machine runners. I'm glad we can discuss it here. We gave it some thoughts a while back, and what you are describing is close to what we envisioned. It's simple and delegates a lot on the user, so it makes the implementation simpler.

I'd see something like this:

```yaml
jobs:
  job1:
    runner: windows
    workspace:
      keep:
        - file1
  job2:
    runner:
      tag: linux
      workspace:
        keep:
          - file1
          - file2
  job3:
    workspace:
      from: job1
    dependencies:
      - job1
      - job2
```

To create the workspace of `job3`, start from workspace of `job1` (configured in `job3.workspace.from`), copy all files `workspace.keep` from `job1`, then from `job2`.

A bit of optimization:
- skip `workspace.keep` of the job configured in `job3.workspace.from`
- when you don't specify `workspace.from` in `job3`, we just use the workspace of the first child (`job1` here)
- when two jobs specify the same file override, we always override previous overrides. Here, `job1` and `job2` define `file1` in their `workspace.keep`, so if `job2` has `file1`, it'll overwrite it.

Some extra thoughts:
- when multiple runner tags are listed, the first runner to pick the job will execute the job (same behavior as currently)
- when no runner tag is defined, any runner can pick the job, unless you have configured `METROLINE_RUNNER_PRIMARY=tag1`
