### ISSUE TITLE
Could not setup repo: Error: Request failed with status code 500 (Gitea)

### ISSUE THREAD

**Issue by vsile** [metroline/metroline#16]
I try to setup my repo. I click "Setup" button and get the next error:
![изображение](https://user-images.githubusercontent.com/9244347/102775355-bf19d600-439d-11eb-9742-8dee1b7f9eda.png)

Logs from docker-compose (server):
```
server_1    | 84dd83eac9d8 1 2020-12-21T11:34:12.538Z error  metroline.server:handleError Error: Request failed with status code 422
server_1    |     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
server_1    |     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
server_1    |     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
server_1    |     at IncomingMessage.emit (events.js:326:22)
server_1    |     at endReadableNT (_stream_readable.js:1223:12)
server_1    |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
server_1    | Error: Thrown at:
server_1    |     at data (/app/src/commons/axios/ensure-stack-trace.ts:6:36)
server_1    |     at t.Gitea.webhook [as addDeployKey] (/app/src/server/git-servers/gitea/gitea.ts:234:13)
server_1    |     at async Promise.all (index 0)
server_1    |     at t.setupRepoRoute (/app/src/server/repos/setup-repo.ts:29:21) 
server_1    | POST /api/v1/repos/5fdcc4016fa5b7b35d49784a/setup 500 120 - 1142.998 ms
```
OAuth and getting repository list work fine. 
Gitea 1.13.0
Gitea API 1.1.1
images: metroline/ui:latest, metroline/server:latest, metroline/runner:latest, mongo:4.2-bionic

How to fix it?

**Comment by vsile** [comment]
Additional info:
We use the next environments:
```
ui:
    ports:
        - "3000:80"
    environment:
        METROLINE_SERVER_URL: https://my.domain.org:9443/server # mapping with proxy to http://10.250.24.40:3001

server:
    ports:
        - "3001:80"
    environment:
        METROLINE_HOST: https://my.domain.org:9443/server # mapping with proxy to http://10.250.24.40:3001
        METROLINE_UI_URL: https://my.domain.org:9443 # mapping with proxy to http://10.250.24.40:3000
```
