### ISSUE TITLE
Installation under traefik v2

### ISSUE THREAD

**Issue by tomaswarynyca** [metroline/metroline#17]
Could you provide a docker compose using metroline under traefik?
It would be very helpful and would be an annex to the documentation.

**Comment by tomaswarynyca** [comment]
I've been trying to make it work under traefik v2. 
I got it, but I don't like the fact that 2 urls have to be exposed.
Did you consider putting the ui and the server in a single container?

**Comment by gempain** [comment]
@tomaswarynyca sorry for the delay. I'm late on this one, but here's what we use for `demo.metroline.io`:

```yaml
version: "3.7"

services:

  traefik:
    image: registry.charlie-bravo.be/traefik:${TRAEFIK_VERSION:-latest}
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Web redirect
      - "--entrypoints.web-redirect.address=:80"
      - "--entrypoints.web-redirect.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web-redirect.http.redirections.entryPoint.scheme=https"
      # Web secure
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL?LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    ports:
      - ${PUBLIC_IP?PUBLIC_IP}:80:80
      - ${PUBLIC_IP?PUBLIC_IP}:443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_DIRECTORY?DATA_DIRECTORY}/letsencrypt:/letsencrypt

  server:
    image: metroline/server:${BACKEND_VERSION:-latest}
    restart: unless-stopped
    environment:
      METROLINE_HOST: https://${METROLINE_DOMAIN?METROLINE_DOMAIN}
      METROLINE_UI_URL: https://${METROLINE_DOMAIN?METROLINE_DOMAIN}
      METROLINE_GITHUB_CLIENT_ID: ${CLIENT_ID?CLIENT_ID}
      METROLINE_GITHUB_CLIENT_SECRET: ${CLIENT_SECRET?CLIENT_SECRET}
      METROLINE_JWT_SECRET: ${METROLINE_JWT_SECRET?METROLINE_JWT_SECRET}
      METROLINE_RUNNER_SECRET: ${METROLINE_RUNNER_SECRET?METROLINE_RUNNER_SECRET}
      METROLINE_MONGO_URI: mongodb://mongo:27017/metroline
      METROLINE_ORGS: metroline
      METROLINE_REQUIRE_LOGIN_FOR_PUBLIC_REPOS: "false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-public.entrypoints=websecure"
      - "traefik.http.routers.backend-public.rule=Host(`${METROLINE_DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/socket.io`))"
      - "traefik.http.routers.backend-public.tls=true"
      - "traefik.http.routers.backend-public.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend-public.service=backend-public"
      - "traefik.http.services.backend-public.loadbalancer.server.port=80"

  ui:
    image: metroline/ui:${UI_VERSION:-latest}
    restart: unless-stopped
    environment:
      METROLINE_SERVER_URL: https://${METROLINE_DOMAIN?METROLINE_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-public.entrypoints=websecure"
      - "traefik.http.routers.frontend-public.rule=Host(`${METROLINE_DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.frontend-public.tls=true"
      - "traefik.http.routers.frontend-public.middlewares=compress"
      - "traefik.http.routers.frontend-public.service=frontend-public"
      - "traefik.http.services.frontend-public.loadbalancer.server.port=80"
      - "traefik.http.middlewares.compress.compress=true"

  runner-1:
    image: metroline/runner:${RUNNER_VERSION:-latest}
    restart: unless-stopped
    environment:
      METROLINE_SERVER_ADDRESS: http://server
      METROLINE_RUNNER_SECRET: secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:${MONGO_VERSION:-4.2-bionic}
    restart: unless-stopped
    volumes:
      - ${DATA_DIRECTORY?DATA_DIRECTORY}/mongo:/data/db
```

I do agree that having Docker images for the backend and for the frontend is odd, but it makes things a lot more simple for development. There could indeed be a macro image with both the UI and the server, we actually did this for [getmelimeli](https://github.com/getmeli/meli) but haven't aligned Metroline on it yet. We could use Caddy or Traeffik, though Caddy is lighter IMO.

**Comment by gempain** [comment]
@tomaswarynyca sorry for the delay. I'm late on this one, but here's what we use for `demo.metroline.io`:

```yaml
version: "3.7"

services:

  traefik:
    image: registry.charlie-bravo.be/traefik:${TRAEFIK_VERSION:-latest}
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Web redirect
      - "--entrypoints.web-redirect.address=:80"
      - "--entrypoints.web-redirect.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web-redirect.http.redirections.entryPoint.scheme=https"
      # Web secure
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL?LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    ports:
      - ${PUBLIC_IP?PUBLIC_IP}:80:80
      - ${PUBLIC_IP?PUBLIC_IP}:443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_DIRECTORY?DATA_DIRECTORY}/letsencrypt:/letsencrypt

  server:
    image: metroline/server:${BACKEND_VERSION:-latest}
    restart: unless-stopped
    environment:
      METROLINE_HOST: https://${METROLINE_DOMAIN?METROLINE_DOMAIN}
      METROLINE_UI_URL: https://${METROLINE_DOMAIN?METROLINE_DOMAIN}
      METROLINE_GITHUB_CLIENT_ID: ${CLIENT_ID?CLIENT_ID}
      METROLINE_GITHUB_CLIENT_SECRET: ${CLIENT_SECRET?CLIENT_SECRET}
      METROLINE_JWT_SECRET: ${METROLINE_JWT_SECRET?METROLINE_JWT_SECRET}
      METROLINE_RUNNER_SECRET: ${METROLINE_RUNNER_SECRET?METROLINE_RUNNER_SECRET}
      METROLINE_MONGO_URI: mongodb://mongo:27017/metroline
      METROLINE_ORGS: metroline
      METROLINE_REQUIRE_LOGIN_FOR_PUBLIC_REPOS: "false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-public.entrypoints=websecure"
      - "traefik.http.routers.backend-public.rule=Host(`${METROLINE_DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/socket.io`))"
      - "traefik.http.routers.backend-public.tls=true"
      - "traefik.http.routers.backend-public.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend-public.service=backend-public"
      - "traefik.http.services.backend-public.loadbalancer.server.port=80"

  ui:
    image: metroline/ui:${UI_VERSION:-latest}
    restart: unless-stopped
    environment:
      METROLINE_SERVER_URL: https://${METROLINE_DOMAIN?METROLINE_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-public.entrypoints=websecure"
      - "traefik.http.routers.frontend-public.rule=Host(`${METROLINE_DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.frontend-public.tls=true"
      - "traefik.http.routers.frontend-public.middlewares=compress"
      - "traefik.http.routers.frontend-public.service=frontend-public"
      - "traefik.http.services.frontend-public.loadbalancer.server.port=80"
      - "traefik.http.middlewares.compress.compress=true"

  runner-1:
    image: metroline/runner:${RUNNER_VERSION:-latest}
    restart: unless-stopped
    environment:
      METROLINE_SERVER_ADDRESS: http://server
      METROLINE_RUNNER_SECRET: ${METROLINE_RUNNER_SECRET?METROLINE_RUNNER_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:${MONGO_VERSION:-4.2-bionic}
    restart: unless-stopped
    volumes:
      - ${DATA_DIRECTORY?DATA_DIRECTORY}/mongo:/data/db
```

I do agree that having Docker images for the backend and for the frontend is odd, but it makes things a lot more simple for development. There could indeed be a macro image with both the UI and the server, we actually did this for [getmelimeli](https://github.com/getmeli/meli) but haven't aligned Metroline on it yet. We could use Caddy or Traeffik, though Caddy is lighter IMO.
