### ISSUE TITLE
Add support for overwriting an image's entrypoint and building Docker images with Kaniko

### ISSUE THREAD

**Issue by fernandodeperto** [metroline/metroline#27]
Currently it doesn't look like it's possible to overwrite an image's entrypoint in a job. Something like this:
```
version: '1'
jobs:
  build:
    image: gcr.io/kaniko-project/executor:debug
    entrypoint: ""
    script:
      - echo I'm alive!
```

In the case of this image, it might also be possible to use `/busybox/sh` as entrypoint, but it might conflict with the way the `bin` argument is used on Metroline. 

This is the output from the job currently:
```
Pulling from kaniko-project/executor
Digest: sha256:9cd309e40375d75bc1293522e3410e1f37f99cd9b8463f0151ecc6621593951b
Status: Image is up to date for gcr.io/kaniko-project/executor:debug
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "process_linux.go:91: executing setns process caused \"exit status 21\"": unknown

command exited with code 126
```

Sources:
[[1]](https://github.com/GoogleContainerTools/kaniko#debug-image) Kaniko image's documention mentioning the entrypoint
[[2]](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html#building-a-docker-image-with-kaniko) Gitlab CI's documentation showing how to build Docker images with Kaniko
