### ISSUE TITLE
Conditional Execution when new tag is created / a git event is triggered

### ISSUE THREAD

**Issue by cking** [metroline/metroline#36]
I am switching from drone to this.

One thing i loved about drone conditional execution is the ability to execute a step only when an (event)[https://docs.drone.io/pipeline/docker/syntax/conditions/#by-event] has been created.

```yml
when:
  event:
  - push
  - pull_request
  - tag
  - promote
  - rollback
```

Only push, pull_request and tag would be enough for me to fully embrace metroline.
