### ISSUE TITLE
[Bug] Entrypoint exec format error

### ISSUE THREAD

**Issue by piotrczarnecki01** [metroline/metroline#40]
Hi everybody.
When I tried to deploy metroline on my server, I noticed that server and UI cannot startup because of `docker-entrypoint.sh: exec format error`.
![image](https://user-images.githubusercontent.com/21225999/209870374-25c2f590-258a-4a2c-b8d2-465b8b8dbec5.png)
![image](https://user-images.githubusercontent.com/21225999/209870457-191e3d5b-266e-4794-b4ed-2dd6df64eb66.png)
My `docker-compose.yml` (I replaced my domain with example.com, all subdomains are left as they were configured):
```
version: "3"

services:
  # UI server is proxied by apache from port 3000 to 443 with SSL
  ui:
    image: metroline/ui:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      METROLINE_SERVER_URL: https://server.metroline.example.com
  # This is also proxied to different subdomain
  server:
    image: metroline/server:latest
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      METROLINE_HOST: https://server.metroline.example.com
      METROLINE_UI_URL: https://metroline.example.com
      METROLINE_JWT_SECRET: XXX
      METROLINE_RUNNER_SECRET: XXX
      METROLINE_MONGO_URI: mongodb://mongo:27017/metroline
      METROLINE_GITEA_CLIENT_ID: XXX
      METROLINE_GITEA_CLIENT_SECRET: XXX
      METROLINE_GITEA_URL: https://gitea.example.com
  mongo:
    image: mongo:4.2-bionic
    restart: unless-stopped
    volumes:
      - metroline-mongo:/data/db
  # Runner is deployed on another, better machine to handle more of them
volumes:
  metroline-mongo:
```
What's better 😄, I tried to deploy whole same configuration on my local machine with portainer and it works idk why, because I try to run this on a clean machine (Ubuntu 22.04.1 LTS) with docker and apache installed and docker-compose makes this strange errors.

Any ideas? Thanks for help and good piece of software!
